### ISSUE TITLE
Error when get Card token for Credit Card Payment

### ISSUE THREAD

**Issue by yuliantosb** [rizdaprasetya/Midtrans-Payment-API-Postman-Collections#2]
Hello @rizdaprasetya I try to using core api from postman collection, but I got an error when request a card token, all params is valid but the api send me a response like this

`{
    "status_code": "402",
    "status_message": "No MID/TID for this transaction",
    "id": "80d95900-d4b7-431a-b5de-057eccf88eca"
}`

my url param like this :

`https://api.sandbox.midtrans.com/v2/token?client_key=VT-client-*************&gross_amount=10000&card_number=4011111111111112&card_exp_month=01&card_exp_year=20&card_cvv=123&secure=true`

any solution for this problem? Thanks

**Comment by rizdaprasetya** [comment]
Hi @yuliantosb seems like your sandbox account is inactive for long time, so it might get temporary disabled, can you share the Merchant ID? so we can check

**Comment by yuliantosb** [comment]
Yeah, I use this account for testing only, is that okay?

my merchant id : M109165

**Comment by rizdaprasetya** [comment]
Hi @yuliantosb please try again now, it should have been active.

It's ok for testing only. But sometime our sandbox during migration (which rarely happens) skipped migrating old merchant account that have no transactions more than a month.

**Comment by yuliantosb** [comment]
Perfect, It's work perfectly, thanks for your support :+1:
