### ISSUE TITLE
[Question] is API for check BIN Card Type deprecated?

### ISSUE THREAD

**Issue by yuliantosb** [rizdaprasetya/Midtrans-Payment-API-Postman-Collections#3]
Hello, @rizdaprasetya  It's me again :D 
I have a question, when I read the documentation midtrans also can check a BIN card info, 
`https://api-docs.midtrans.com/#bin-api`
When I try it, I got an error response
```
{
    "errors": [
        {
            "message_title": "not found",
            "message": "not found"
        }
    ]
}
```

Is that not available for now or deprecated? Because I can't find it on postman collection that I've downloaded from this repository

**Comment by rizdaprasetya** [comment]
Hi @yuliantosb this is a relatively new API endpoint, and have not yet added to the postman collections.
I just tested the API is working fine, can you try to import this to Postman (or exec the CURL)
```
curl --request GET \
	--url https://api.sandbox.midtrans.com/v1/bins/481111 \
	--header 'accept: application/json' \
	--header 'authorization: Basic <BASE64ENCODEDKEY>' \
	--header 'content-type: application/json' 
```
Don't forget to change the `authorization` part.

**Comment by rizdaprasetya** [comment]
Also next time for faster Midtrans response please email the questions to support@midtrans.com
Thanks.

**Comment by yuliantosb** [comment]
Oh, so I just put 6 digits instead of full card number?
Thanks, for you answer

**Comment by rizdaprasetya** [comment]
Yes BIN identifier is usually just 4-6 first digit, which represents the bank/brand/issuer
